// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEmTgQSYuQUkH-RVMb4KChuvTw7w-TBQ4',
    appId: '1:296688137597:web:e5226e3ebd9c8780360814',
    messagingSenderId: '296688137597',
    projectId: 'flutter-firebase-dersler-986f4',
    authDomain: 'flutter-firebase-dersler-986f4.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-986f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC16N3P0qIo26NQzoLVZpKx6sxv2M_AafE',
    appId: '1:296688137597:android:80643c43c3d80981360814',
    messagingSenderId: '296688137597',
    projectId: 'flutter-firebase-dersler-986f4',
    storageBucket: 'flutter-firebase-dersler-986f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqljRJ3NmQgp88tk1U49UBiD717bApJnE',
    appId: '1:296688137597:ios:df0da25f1e5bb443360814',
    messagingSenderId: '296688137597',
    projectId: 'flutter-firebase-dersler-986f4',
    storageBucket: 'flutter-firebase-dersler-986f4.appspot.com',
    iosBundleId: 'com.developer.flutterFirebaseDersleri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqljRJ3NmQgp88tk1U49UBiD717bApJnE',
    appId: '1:296688137597:ios:df0da25f1e5bb443360814',
    messagingSenderId: '296688137597',
    projectId: 'flutter-firebase-dersler-986f4',
    storageBucket: 'flutter-firebase-dersler-986f4.appspot.com',
    iosBundleId: 'com.developer.flutterFirebaseDersleri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEmTgQSYuQUkH-RVMb4KChuvTw7w-TBQ4',
    appId: '1:296688137597:web:f6a5336dab617620360814',
    messagingSenderId: '296688137597',
    projectId: 'flutter-firebase-dersler-986f4',
    authDomain: 'flutter-firebase-dersler-986f4.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-986f4.appspot.com',
  );
}
